### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by Lunatixz** [stereodruid/plugin.video.pseudo.library#2]
@stereodruid please push the changes you made so that we can review them.

Also if you've experienced issues with compatibility. Can you describe the problem? Thanks

**Comment by Lunatixz** [comment]
@stereodruid I noticed in #1 you voiced concern if I'd accept your code... because "you are not a developer".

Don't worry about that... everyone has to start somewhere. Just push your working code and comment out anything you know doesn't work. 

Leave me comments in regards to what's wrong, and what you want to do. From there we can work out the specifics.

**Comment by stereodruid** [comment]
@Lunatixz i pushed my changes. The code is as simple as possible for me and should be universal. The new category is meant for content that is not conform wel formed like here:
http://kodi.wiki/view/naming_video_files/TV_shows

It will work also with xStream: https://github.com/Lynx187/plugin.video.xstream
By the way it is not illegal, it is a gray zone for us in Germany.

I still have problems when filenames contain german umlauts like: Ä,Ö,Ü,ß.
Any idea?

**Comment by stereodruid** [comment]
Now it should work, i just pushed the wrong files before.

**Comment by Lunatixz** [comment]
filenames is a encoding issue... I'll take a look. Thanks for the updates :)

**Comment by stereodruid** [comment]
This is the error:
The original file name is "Grey's Anatomy - Die jungen Ärzte "
```
                                   - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', "C:\\Users\\J\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.pseudo.library\\strms\\TV-Shows\\Grey's Anatomy - Die jungen \xc3\x84rzte \\s1e1.strm")
                                            Traceback (most recent call last):
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\default.py", line 622, in <module>
                                                fillPluginItems(url, strm=True, strm_name=name, strm_type=type)
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\default.py", line 245, in fillPluginItems
                                                fillPluginItems(file, media_type, file_type, strm, label, strm_type)
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\default.py", line 239, in fillPluginItems
                                                writeSTRM(cleanStrms(path), cleanStrms(filename) ,link)
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\default.py", line 371, in writeSTRM
                                                makeSTRM(path, file, url)
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\default.py", line 362, in makeSTRM
                                                fle = open(fullpath, "w")
                                            IOError: (2, 'No such file or directory', "C:\\Users\\J\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.pseudo.library\\strms\\TV-Shows\\Grey's Anatomy - Die jungen \xc3\x84rzte \\s1e1.strm")
                                            -->End of Python script error report<--
```

**Comment by Lunatixz** [comment]
use ascii function, file = open(ascii(fullpath), "w")

**Comment by stereodruid** [comment]
#1

**Comment by stereodruid** [comment]
Unfortunately not the solution.
Still getting:
```
116:26:46 T:11600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', "C:\\Users\\J\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.pseudo.library\\strms\\TV-Shows\\Grey's Anatomy - Die jungen \xc3\x84rzte \\s1e1.strm")
                                            Traceback (most recent call last):
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\service.py", line 77, in <module>
                                                strm_update()
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\service.py", line 73, in strm_update
                                                default.fillPluginItems(url, strm=True, strm_name=name, strm_type=type)
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\default.py", line 248, in fillPluginItems
                                                fillPluginItems(file, media_type, file_type, strm, label, strm_type)
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\default.py", line 242, in fillPluginItems
                                                writeSTRM(cleanStrms(path), cleanStrms(filename) ,link)
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\default.py", line 374, in writeSTRM
                                                makeSTRM(path, file, url)
                                              File "C:\Users\J\AppData\Roaming\Kodi\addons\plugin.video.pseudo.library\default.py", line 365, in makeSTRM
                                                fle = open(fullpath, "w")
                                            **_IOError: (2, 'No such file or directory', "C:\\Users\\J\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.pseudo.library\\strms\\TV-Shows\\Grey's Anatomy - Die jungen \xc3\x84rzte \\s1e1.strm")_**
                                            -->End of Python script error report<--
```

**Comment by Lunatixz** [comment]
I don't see the ascii function being called in the log, are you sure you edited the proper line of code and correct file?
```
line 365, in makeSTRM
                                                fle = open(fullpath, "w")
```

**Comment by stereodruid** [comment]
Yes I did.
if i request the default encoding like this:
sys.getdefaultencoding(), return is "utf8" 

I will push my changes

Thanks for your help.

**Comment by Lunatixz** [comment]
avoid sys.getdefault, this isn't the proper way to handle encoding...

I don't have your example setup here so I can't see the original bytestring... I assumed it was ascii... instead of using the ascii function use the "uni" function and please remove the sys.getdefault... Does it work now?

**Comment by stereodruid** [comment]
I removed the sys.getdefault and changed also ascii to uni. still not working :(

**Comment by stereodruid** [comment]
I tried the below code and it work this way.
I have no idea why. It is a ugly solution but i am tired of searching for a nice solution.
```
showtitle = utils.multiple_reSub(uni((showtitles.group(1)).rstrip()), dictReplacements) 

dictReplacements = {'\\([^)]*\\)' : '', "'.'" : ' ', '\xc3\x84' : 'Ae',
                            '\xc3\xa4' : 'ae', '\xc3\x96' : 'Oe', '\xc3\xb6' : 'oe',
                            '\xc3\x9c' : 'Ue', 'xc3\xbc' : 'ue', '\xc3\x9f' : 'ss'}

#***************************************************************************************
# Python Header 
#        multiple_reSub
# Purpose:
#        reSub all strings insite a dict. Valuse in dict:
# dictReplacements = {'search1' : 'replace with1', 'search2' : 'replace with2'} 
# Author:
#        stereodruid(J.G.)
# History:
#        0 - init 
def multiple_reSub(text, dic):
    for i, j in dic.iteritems():
        text = re.sub(i, j, text)
    return text
```

**Comment by stereodruid** [comment]
So if this table I found  is correct, it shouldn't cause any other problems with other languages, i guess.

Table:
Ä = \xc3\x84
ä = \xc3\xa4
Ö = \xc3\x96
ö = \xc3\xb6
Ü = \xc3\x9c
ü = \xc3\xbc
ß = \xc3\x9f

**Comment by Lunatixz** [comment]
I'll check it out tonight... thanks

**Comment by Lunatixz** [comment]
Please open a pull request to my source, create a new branch.

BTW now that you are a team member you can push code directly to my source :) so a fork isn't needed. 

Kevin
